### ISSUE TITLE
How about the training speed of SFD?

### ISSUE THREAD

**Issue by BunnyShan** [sfzhang15/SFD#16]
Simply add conv3_3 will makes the training speed drop significant, could you explain what's the solution about this issue?

**Comment by sfzhang15** [comment]
@BunnyShan 
Hi, the size of conv3_3 is large, and adding conv3_3 as detection layer will also bring some layers (i.e., cls and reg layer) with the same size. Besides, the number of anchors associated with this layer is also large. So adding conv3_3 as detection layer will inevitably lead to slow training. If you want to speed up, we suggest you associate the 16x16 anchor with the conv4_3.

**Comment by BunnyShan** [comment]
@sfzhang15 Thanks for your reply. But associate 16x16 anchor to conv4_3 will make the anchor stride half of the size, and the RF maybe too large for 16x16 anchor. How much impact will this settings cause?

**Comment by sfzhang15** [comment]
@BunnyShan  The larger RF is ok since it can provide some context information. But the tiling interval of 16x16 anchors and the stride size of conv4_3 is a bit large, which will affect the detection of tiny faces, while has no impact on the detection of medium and large faces, even slightly improves their detection performance.

**Comment by BunnyShan** [comment]
Thanks a lot. I will close this issue.

**Comment by foralliance** [comment]
@sfzhang15 
 "Designing scales for anchors"  of section 3.1 points out that : 
`the anchor should be significantly smaller than theoretical receptive field in order to match theeffective  receptive field, `

but here you said that 
`the larger the RF is ok since it can dojo.provide some context information`

**Is it a contradiction?**

**Comment by sfzhang15** [comment]
@foralliance 
We hope the anchor to match the effective receptive field, since the effective receptiver field only can be estimated, so we think it's more appropriate to use this word 'match'. We think it may be better that the anchor is slightly smaller than the effective receptive field to provide some useful information.

**Comment by foralliance** [comment]
According to you said: `associate 16x16 anchor to conv4_3`．

Now, the anchor size = 16, and TRF = 108. I think it goes against your design principles: **small face, anchor scale and receptive field to match**.

because when TRF = 108, its corresponding ERF should also be large，it can't match the anchor size.

**Comment by sfzhang15** [comment]
@foralliance 
The 16x16 anchor is associated with conv3_3 whose TRF is 48.
