### ISSUE TITLE
Unable to merge SFD with official caffe

### ISSUE THREAD

**Issue by yxchng** [sfzhang15/SFD#23]
Hi, I am unable to merge SFD(SSD) with the original Caffe. Do you happen to know any way that I can do that? Thanks

**Comment by sfzhang15** [comment]
@yxchng Hi，
Our SFD is based on SSD-caffe. Comparing with the official caffe, there are lots of modifications in SSD-caffe, i.e., adding some layers and functions. So if you want merge SSD with the official caffe, maybe you need modify the official caffe like SSD. If the cudnn in SSD-caffe has problem, since it only support cudnn 5 or 5.1,  you can replace the cudnn.h in SSD-caffe with the new cudnn.h in the official caffe.
