### ISSUE TITLE
Train for Person Detection

### ISSUE THREAD

**Issue by ahkarami** [sfzhang15/SFD#24]
Dear @sfzhang15,
Thank you for your fantastic work. Have you ever trained your model for _person detection_?

**Comment by sfzhang15** [comment]
@ahkarami Hi,
We do not have the plan to train our SFD method for person detection.

**Comment by ahkarami** [comment]
@sfzhang15,
Ok. Thank you for your reply. Just as another question. What's your prediction about its accuracy for person detection? (In fact, I mean that, the accuracy & performance of your face detector model is very great. Regarding the fact that your model is _Scale-Invariant_, so I thought myself that this model can detect person as well as face.  Am I correct?)

**Comment by sfzhang15** [comment]
@ahkarami 
Comparing with face detection in which the scale may be the main issue, we think person detection has some different challenges, since the person is deformable and there is more occlusion. You can apply some tricks in face detection for person detection, but we think maybe it is not enough. You should use some tricks to deal with its specific problems, such as deformable body, occulsion case and son on.
