### ISSUE TITLE
error == cudaSuccess(2 vs 0) out of memory

### ISSUE THREAD

**Issue by tzhang2014** [sfzhang15/SFD#42]
When I run the wider_test.py, it meet the problem of out of memory, but  I use single picture to run,it works.

**Comment by sfzhang15** [comment]
@tzhang2014 
The wider_test.py uses multi-scale testing. What is your GPU memory?

**Comment by tzhang2014** [comment]
@sfzhang15  my GPU memory is 8G , when I run nvidia-smi , I can see the  usage of  program is 6.5G ,

**Comment by sfzhang15** [comment]
@tzhang2014 
You can refer to [this issue](https://github.com/sfzhang15/SFD/issues/17) to see whether it can solve your problem or not.

**Comment by fatporkchop** [comment]
Hi Shifeng, thank you for your huge contribution.

I am currently facing the same problem with memory: error == cudaSuccess(2 vs 0) out of memory

I noticed that decreasing my batch_size from 32 as per written in your paper to 4 resolves the issue. However, I do not understand why this is the case. You mentioned that you use titian x (Maswell) with cuda-8.0 and cudnn-6.0. I am also using cuda-8.0 and cudnn-6.0 with 2 titanx 12gb but use 9.1gb ram on each GPU when my batch size is 4.

The following are my implementation steps:
1. Cloned SSD code
2. Created image lmdb files
3. Installed Caffe and all dependencies
4. Modified data augmentation code so that it doesn't change image ratio. Then proceeded to build the code
5. Download your trained model from GoogleDrive or BaiduYun, and merge it with the folder $SFD_ROOT/models
6. Used the prototxt files (deploy, solver and train) in the directory /models/VGGNet/WIDER_FACE/SFD
7. Ran training code

**Comment by sfzhang15** [comment]
@fatporkchop 
Soory about that, we do not know the reason. For our Titan X (Maswell ), it can have 8 images per GPU. You can try original SSD code to check whether the memory usage is right.

**Comment by sfzhang15** [comment]
@fatporkchop 
Do you make caffe with cudnn?

**Comment by fatporkchop** [comment]
@sfzhang15 
Checked original SSD code, memory usage is right.
I didn't, but i just retried it after making caffe with cudnn, still the same issue.

**Comment by fatporkchop** [comment]
@sfzhang15 

Can I confirm the following please?

In this thread, [https://github.com/sfzhang15/SFD/issues/32](url), you mentioned "For 640x640 input image with 32 batch size, we use 2 Titan X (maswell) GPUs to train our model"

I'm currently using 8 batch_size (in my train.prototxt under data_param) with 2 Titan X 12GB GPUs with 640x640 input but my memory is capped where i'm already using 11.4GB for each GPU, and thus I cannot further increase my batch_size.

So may I know how you realised effective batch size 32? Was batch_size in train.prototxt set to 16 in your case such that 2x16 =32? Or was it trained with 4 GPUs with batch_size 8, because the default train.prototxt came with batch_size 8?

Thank you very much!! :+1:

**Comment by sfzhang15** [comment]
@fatporkchop 
We ues batch_size=8 with 2 GPUs and **iter_size=2**, so the accumulated batch size is 8x2x2=32.
