### ISSUE TITLE
The performance of the pretrained model you provided is somewhat different from?

### ISSUE THREAD

**Issue by takecareofbigboss** [sfzhang15/SFD#8]
![image](https://user-images.githubusercontent.com/11883059/33423763-c2599d06-d5f4-11e7-9a16-3ccecc14c7d0.png)

Hi, i tested the pretrained model you provided, and found that the performance is somewhat different from shown on the official website?  is this model the best of your algorithm?
The performance i got is 93.8/ 92.5/ 84.8 ...

**Comment by takecareofbigboss** [comment]
@sfzhang15

**Comment by sfzhang15** [comment]
@takecareofbigboss Hi, We have already explained this difference in README.md as follow:
# If you want to get the results of val set in our paper, you should use the provided "eval_tools_old-version". 
# Or you can use latest eval_tools of WIDER FACE.
# There is a slight difference between them, since the annotation used for the evaluation is slightly change around March 2017.

**Comment by takecareofbigboss** [comment]
@sfzhang15  ok IC, thanks for ur reply.
